version: 2.1
jobs:
  snapshot-build-on-branch:
    working_directory: ~/cafienne-ide
    docker:
      - image: cimg/node:8.17.0
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: sudo chmod -R 777 ./
      - run:
          name: Installing dependencies
          command: |
            npm install
            sudo npm install bower -g
            bower install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ];
            then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker build -t cafienne/ide:latest .
            else
              echo "Building docker image cafienne/ide:snapshot"
              docker build -t cafienne/ide:snapshot .
            fi
      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            if [ "${CIRCLE_BRANCH}" == "main" ];
            then
              echo "Publishing image 'cafienne/ide:latest' to docker hub"
              docker push cafienne/ide:latest
            else
              echo "Publishing image 'cafienne/ide:snapshot' to docker hub"
              docker push cafienne/ide:snapshot
            fi

  latest-build-on-main:
    working_directory: ~/cafienne-ide
    docker:
      - image: cimg/node:8.17.0
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: sudo chmod -R 777 ./
      - run:
          name: Check for version TAG
          command: |
            echo `git describe --tags --exact-match` > ./version.txt
            cat ./version.txt
            TAG=$(cat ./version.txt)
            printenv
      - run:
          name: Installing dependencies
          command: |
            npm install
            sudo npm install bower -g
            bower install
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build -t cafienne/ide:$CIRCLE_TAG .
      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push cafienne/ide:$CIRCLE_TAG

workflows:
  version: 2
  ci:
    jobs:
      - snapshot-build-on-branch:
          context: automation-context
      - latest-build-on-main:
          context: automation-context
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/